services:
  floci:
    image: floci/floci:latest
    container_name: simulador-aws
    ports:
      - "4566:4566"          # endpoint unico de todos os servicos AWS
    volumes:
      # Local directory bind mount (default)
      - ./data:/app/data

      # Docker socket — required for Lambda (and RDS/ElastiCache/OpenSearch/MSK/ECS)
      - /var/run/docker.sock:/var/run/docker.sock

      # OR named volume (optional):
      # - floci-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

#volumes:
#  floci-data:
